"""Project initialization and management handler."""

from __future__ import annotations

import pathlib
from typing import Any

from moira_cli.handlers import BaseHandler
from moira_cli.io import (
    check_prereqs,
    ensure_local_env,
    load_moiraweave_config,
    scaffold_workspace_structure,
    write_default_moiraweave_config,
)

_COMPOSE_CONTENT = """\
# Generated by `moira init` — managed by MoiraWeave CLI.
# Platform services: api-gateway, worker, postgres, redis, qdrant, ui.
# Workload services can be generated by `moira deploy local`.
# Do not commit this file if you store secrets in .env.
#
# Start the local platform:
#   docker compose up -d
#   open http://localhost:${MOIRAWEAVE_UI_PORT:-3000}
services:
  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - moiraweave-net
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-moiraweave}
      POSTGRES_USER: ${POSTGRES_USER:-moiraweave}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-moiraweave-dev}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - moiraweave-net
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-moiraweave} -d ${POSTGRES_DB:-moiraweave}"]
      interval: 5s
      timeout: 3s
      retries: 10

  qdrant:
    image: qdrant/qdrant:v1.9.2
    ports:
      - "${QDRANT_PORT:-6333}:6333"
    networks:
      - moiraweave-net
    volumes:
      - qdrant_data:/qdrant/storage

  worker:
    image: ${MOIRAWEAVE_WORKER_IMAGE:-ghcr.io/moiraweave-labs/moiraweave/worker:latest}
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379
      POSTGRES_DSN: postgresql://${POSTGRES_USER:-moiraweave}:${POSTGRES_PASSWORD:-moiraweave-dev}@postgres:5432/${POSTGRES_DB:-moiraweave}
      WORKLOADS_DIR: /workspace/workloads
      ARTIFACTS_DIR: /workspace/artifacts
    networks:
      - moiraweave-net
    volumes:
      - ./.moiraweave/workloads:/workspace/workloads:ro
      - ./.moiraweave/artifacts:/workspace/artifacts

  api-gateway:
    image: ${MOIRAWEAVE_API_GATEWAY_IMAGE:-ghcr.io/moiraweave-labs/moiraweave/api-gateway:latest}
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    ports:
      - "${API_GATEWAY_PORT:-8000}:8000"
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379
      POSTGRES_DSN: postgresql://${POSTGRES_USER:-moiraweave}:${POSTGRES_PASSWORD:-moiraweave-dev}@postgres:5432/${POSTGRES_DB:-moiraweave}
      WORKLOADS_DIR: /workspace/workloads
      ARTIFACTS_DIR: /workspace/artifacts
    networks:
      - moiraweave-net
    volumes:
      - ./.moiraweave/workloads:/workspace/workloads:ro
      - ./.moiraweave/artifacts:/workspace/artifacts

  ui:
    image: ${MOIRAWEAVE_UI_IMAGE:-ghcr.io/moiraweave-labs/moiraweave-ui:latest}
    depends_on:
      api-gateway:
        condition: service_started
    ports:
      - "${MOIRAWEAVE_UI_PORT:-3000}:80"
    environment:
      API_PROXY_PASS: http://api-gateway:8000
    networks:
      - moiraweave-net

volumes:
  redis_data:
  qdrant_data:
  postgres_data:

networks:
  moiraweave-net:
    name: moiraweave-net
"""


class ProjectHandler(BaseHandler):
    """Handle project initialization and management."""

    def init_workspace(
        self,
        project_name: str | None = None,
        registry: str | None = None,
    ) -> dict[str, Any]:
        """Initialize a new workspace.

        :param project_name: Optional project name (defaults to directory name).
        :param registry: Optional OCI registry (defaults to ghcr.io/myorg).
        :returns: Dictionary with created paths and status.
        """
        config_path = self.repo_root / "moiraweave.yaml"

        # Check if already initialized
        if config_path.exists():
            return {
                "status": "already_initialized",
                "config_path": config_path,
                "config": load_moiraweave_config(self.repo_root),
                "prereqs": check_prereqs(),
            }

        # Use defaults if not provided
        final_name = project_name or self.repo_root.name
        final_registry = registry or "ghcr.io/myorg"

        # Write configuration and scaffold
        write_default_moiraweave_config(self.repo_root, final_name, final_registry)
        ensure_local_env(self.repo_root)
        scaffold_workspace_structure(self.repo_root)
        _write_docker_compose(self.repo_root)

        return {
            "status": "created",
            "project_name": final_name,
            "registry": final_registry,
            "config_path": config_path,
            "env_path": self.repo_root / ".env",
            "directories": [
                self.repo_root / ".moiraweave" / "workloads",
                self.repo_root / ".moiraweave" / "artifacts",
                self.repo_root / ".moiraweave" / "deploy",
            ],
        }

    def get_status(self) -> dict[str, Any]:
        """Get current project status.

        :returns: Dictionary with project metadata.
        """
        config_path = self.repo_root / "moiraweave.yaml"
        if not config_path.exists():
            return {"status": "not_initialized"}

        config = load_moiraweave_config(self.repo_root)
        return {
            "status": "initialized",
            "name": config.name,
            "registry": config.registry,
            "runtime_version": config.runtime_version,
            "environments": list(config.environments.keys()),
            "prereqs": check_prereqs(),
        }


def _write_docker_compose(repo_root: pathlib.Path) -> None:
    """Write docker-compose.yml to the workspace root if it does not exist.

    :param repo_root: Workspace root directory.
    """
    compose_path = repo_root / "docker-compose.yml"
    if not compose_path.exists():
        compose_path.write_text(_COMPOSE_CONTENT, encoding="utf-8")
