"""Filesystem helpers for MoiraWeave CLI."""

from __future__ import annotations

import secrets
import shutil
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pathlib import Path

import yaml
from dotenv import dotenv_values
from pydantic import ValidationError

from moira_cli.models import MoiraWeaveConfig


def load_moiraweave_config(repo_root: Path) -> MoiraWeaveConfig:
    """Load and validate moiraweave.yaml from repository root.

    :param repo_root: Repository root path.
    :returns: Parsed project configuration.
    :raises FileNotFoundError: If moiraweave.yaml does not exist.
    :raises ValueError: If the file is invalid.
    """
    config_path = repo_root / "moiraweave.yaml"
    if not config_path.exists():
        raise FileNotFoundError("moiraweave.yaml not found")

    raw = yaml.safe_load(config_path.read_text(encoding="utf-8"))
    try:
        return MoiraWeaveConfig.model_validate(raw)
    except ValidationError as exc:  # pragma: no cover - formatting branch
        raise ValueError(f"Invalid moiraweave.yaml: {exc}") from exc


def write_default_moiraweave_config(repo_root: Path, name: str, registry: str) -> None:
    """Write a default moiraweave.yaml file.

    :param repo_root: Repository root path.
    :param name: Project name.
    :param registry: Image registry URL.
    """
    config = {
        "name": name,
        "registry": registry,
        "runtime_version": "0.1.0",
        "environments": {
            "local": {"context": "docker-compose", "values": ".env"},
            "dev": {
                "context": "kubernetes",
                "kubeconfig": "~/.kube/config",
                "namespace": "moiraweave-dev",
                "helm_values": ".moiraweave/deploy/values-dev.yaml",
                "deploy": "helm",
            },
            "prod": {
                "context": "kubernetes",
                "namespace": "moiraweave-prod",
                "helm_values": ".moiraweave/deploy/values-prod.yaml",
                "deploy": "helm",
            },
        },
        "workloads_dir": ".moiraweave/workloads",
        "artifacts_dir": ".moiraweave/artifacts",
        "deploy_dir": ".moiraweave/deploy",
    }
    target = repo_root / "moiraweave.yaml"
    target.write_text(yaml.safe_dump(config, sort_keys=False), encoding="utf-8")


def scaffold_workspace_structure(repo_root: Path) -> None:
    """Create complete workspace directory structure.

    Creates:
    - .moiraweave/workloads/ (workload manifests)
    - .moiraweave/artifacts/ (local artifact store)
    - .moiraweave/deploy/ (deployment configuration)
    - .gitignore (sensible defaults)

    :param repo_root: Repository root path.
    """
    dirs = [
        repo_root / ".moiraweave" / "workloads",
        repo_root / ".moiraweave" / "artifacts",
        repo_root / ".moiraweave" / "deploy",
    ]
    for d in dirs:
        d.mkdir(parents=True, exist_ok=True)
        (d / ".gitkeep").touch()

    # Create .gitignore if it doesn't exist
    gitignore_path = repo_root / ".gitignore"
    if not gitignore_path.exists():
        gitignore_content = """.env
.venv/
__pycache__/
*.pyc
*.pyo
*.pyd
.DS_Store
.idea/
.vscode/
*.egg-info/
dist/
build/
.pytest_cache/
.mypy_cache/
"""
        gitignore_path.write_text(gitignore_content, encoding="utf-8")

    # Create deploy values files
    for env in ["local", "dev", "prod"]:
        values_file = repo_root / ".moiraweave" / "deploy" / f"values-{env}.yaml"
        if not values_file.exists():
            values_file.write_text(
                f"# Deployment values for {env} environment\n"
                f"# Override or extend defaults from moiraweave\n"
                f"environment: {env}\n",
                encoding="utf-8",
            )


def ensure_local_env(repo_root: Path) -> None:
    """Create `.env` with safe defaults if it does not exist.

    :param repo_root: Repository root path.
    """
    env_path = repo_root / ".env"
    if env_path.exists():
        return

    secret = secrets.token_urlsafe(32)
    content = (
        "# Auto-generated by moira init\n"
        "# These values are safe for local development but must be reviewed before production.\n"
        "# Do not share this file or commit it to version control.\n"
        f"JWT_SECRET_KEY={secret}\n"
        "JWT_ALGORITHM=HS256\n"
        "JWT_ACCESS_TOKEN_EXPIRE_MINUTES=30\n"
        "API_GATEWAY_PORT=8000\n"
        "MOIRAWEAVE_UI_PORT=3000\n"
        "POSTGRES_PORT=5432\n"
        "REDIS_PORT=6379\n"
        "QDRANT_PORT=6333\n"
        "MOIRAWEAVE_API_GATEWAY_IMAGE=ghcr.io/moiraweave-labs/moiraweave/api-gateway:latest\n"
        "MOIRAWEAVE_WORKER_IMAGE=ghcr.io/moiraweave-labs/moiraweave/worker:latest\n"
        "MOIRAWEAVE_UI_IMAGE=ghcr.io/moiraweave-labs/moiraweave-ui:latest\n"
        "POSTGRES_DB=moiraweave\n"
        "POSTGRES_USER=moiraweave\n"
        "POSTGRES_PASSWORD=moiraweave-dev\n"
    )
    env_path.write_text(content, encoding="utf-8")


def read_env(repo_root: Path) -> dict[str, str]:
    """Read `.env` values from repository root.

    :param repo_root: Repository root path.
    :returns: Env key/value mapping.
    """
    values = dotenv_values(repo_root / ".env")
    return {k: v for k, v in values.items() if v is not None}


def check_prereqs() -> dict[str, bool]:
    """Check local command prerequisites.

    :returns: Mapping with command availability.
    """
    return {
        "docker": shutil.which("docker") is not None,
        "kubectl": shutil.which("kubectl") is not None,
        "helm": shutil.which("helm") is not None,
    }
